# Generated by Django 3.2.15 on 2023-02-09 13:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email_address', models.EmailField(default='email@email.com', max_length=254)),
                ('phone_number', models.IntegerField()),
                ('date_of_booking', models.DateField(default=datetime.datetime(2023, 2, 9, 13, 59, 32, 17909, tzinfo=utc))),
                ('time_of_booking', models.CharField(choices=[('12:00:00', '12pm'), ('12:15:00', '12:15pm'), ('12:30:00', '12:30pm'), ('12:45:00', '12:45pm'), ('13:00:00', '1pm'), ('13:15:00', '1:15pm'), ('13:30:00', '1:30pm'), ('13:45:00', '1:45pm'), ('14:00:00', '2pm'), ('14:15:00', '2:15pm'), ('14:30:00', '2:30pm'), ('14:45:00', '2:45pm'), ('15:00:00', '3pm'), ('15:15:00', '3:15pm'), ('15:30:00', '3:30pm'), ('15:45:00', '3:45pm'), ('16:00:00', '4pm'), ('16:15:00', '4:15pm'), ('16:30:00', '4:30pm'), ('16:45:00', '4:45pm'), ('17:00:00', '5pm'), ('17:15:00', '5:15pm'), ('17:30:00', '5:30pm'), ('17:45:00', '5:45pm'), ('18:00:00', '6pm'), ('18:15:00', '6:15pm'), ('18:30:00', '6:30pm'), ('18:45:00', '6:45pm'), ('19:00:00', '7pm'), ('19:15:00', '7:15pm'), ('19:30:00', '7:30pm'), ('19:45:00', '7:45pm'), ('20:00:00', '8pm'), ('20:15:00', '8:15pm'), ('20:30:00', '8:30pm'), ('20:45:00', '8:45pm'), ('21:00:00', '9pm'), ('21:15:00', '9:15pm'), ('21:30:00', '9:30pm'), ('21:45:00', '9:45pm'), ('22:00:00', '10pm'), ('22:15:00', '10:15pm'), ('22:30:00', '10:30pm'), ('22:45:00', '10:45pm')], default='', max_length=10)),
                ('number_of_people', models.IntegerField()),
                ('special_requests', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
