# Generated by Django 3.2.15 on 2022-09-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone_number', models.IntegerField()),
                ('date_of_booking', models.DateField()),
                ('time_of_booking', models.TimeField()),
                ('number_of_people', models.IntegerField()),
                ('special_requests', models.CharField(max_length=200)),
            ],
        ),
    ]
