# Generated by Django 3.2.15 on 2022-09-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20220918_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_booking',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_people',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_of_booking',
            field=models.TimeField(),
        ),
    ]
