# Generated by Django 3.2.15 on 2023-01-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_of_booking',
            field=models.TimeField(choices=[('12:00:00', '12:00:00'), ('12:15:00', '12:15pm'), ('12:30:00', '12:30pm')]),
        ),
    ]
